// NetflixApiDashboard/src/app/layout/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService, AccountDto } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {
  userEmail: string | null = null;

  constructor(private readonly authService: AuthService) {}

  ngOnInit(): void {
    this.authService.currentAccount$.subscribe((account: AccountDto | null) => {
      this.userEmail = account?.email || null;
    });
  }

  onSignOutClicked(): void {
    this.authService.logout();
  }
}

<div class="navbar">
  <div class="navbar-left">
    <img src="./assets/logo.png" alt="logo" />
    <button class="hamburger-menu" onclick="toggleDropdown()">☰</button>
      <li style="list-style: none;"><a href="/home">Home</a></li>
    <ul class="menu">
      <li><a routerLink="/series">Tv Shows</a></li>
      <li><a href="/movie">Movies</a></li>
      <li><a href="#">New and Popular</a></li>
      <li><a href="#">My List</a></li>
      <li><a href="#">Browse by language</a></li>
    </ul>
  </div>
  <div class="navbar-right">
    <img src="./assets/search_icon.svg" alt="search" class="icons" />
    <p>{{ this.userEmail || 'User Name' }}</p>
    <img src="./assets/bell_icon.svg" alt="bell" class="icons" />
    <div class="navbar-profile">
      <img src="./assets/profile_img.png" alt="profile" class="profile" />
      <img src="./assets/caret_icon.svg" alt="dropdown" />
      <div class="dropdown">
        <p><a routerLink="/settings" class="no-decoration">Settings</a></p>
        <p><a routerLink="/api" class="no-decoration">API</a></p>
        <p style="text-decoration: underline;" (click)="onSignOutClicked()">Sign out</p>
      </div>
    </div>
  </div>
</div>

// Front-End/src/components/Navbar/Navbar.jsx
import React, {useEffect, useRef} from "react";
import './Navbar.css'
import logo from '../../assets/logo.png'
import search_icon from '../../assets/search_icon.svg'
import bell_icon from '../../assets/bell_icon.svg'
import profile_img from '../../assets/profile_img.png'
import dropdown_icon from '../../assets/caret_icon.svg'
import { Link } from 'react-router-dom';




const Navbar = () => {

    const navRef = useRef();

    useEffect(() => {
        window.addEventListener('scroll', ()=>{
            if(window.scrollY >= 80){
                navRef.current.classList.add('nav-dark')
            } else{
                navRef.current.classList.remove('nav-dark')
            }
        })
    }, []);

    return (
        <div ref={navRef} className='navbar'>
            <div className='navbar-left'>
                <img src={logo} alt="Netflix logo"/>
                <ul>
                    <li> <Link to="/" className="no-decoration">Home</Link></li>
                    <li>Tv Shows</li>
                    <li>Movies</li>
                    <li>New and Popular</li>
                    <li>My List</li>
                    <li>Browse by language</li>
                </ul>
            </div>
            <div className='navbar-right'>
                <img src={search_icon} alt='search icon' className='icons'/>
                <p>Name here of user</p>
                <img src={bell_icon} alt='bell icon' className='icons'/>
                <div className='navbar-profile'>
                    <img src={profile_img} alt='bell icon' className='profile'/>
                    <img src={dropdown_icon} alt='bell icon' />
                    <div className='dropdown'>
                        <p><Link to="/API" className='no-decoration'>API</Link></p>
                        <p>Settings</p>
                        <p style={{textDecoration: 'underline'}}>Sign out</p>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Navbar;
